openapi: 3.0.0
info:
  title: Helmsman NFT Storage API
  version: '1.0'

servers:
  - url: http://103.44.247.16:18001

tags:
  - name: Helmsman NFT Storage
paths:
  /api/market/storage/create:
    post:
      tags:
        - 创建存储订单
      summary: Store a file
      description: |
        
        ### 第一步上传文件到IPFS拿到文件Cid
      
        ### 第二步上传文件到Filecoin
        
        备注:单文件最好不要超过100M
      operationId: storageCreate
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/StorageCreateRequest'
      responses:
        '200':
          description: 正常返回，状态码包含在status字段
          content:
            'application/json':
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: 状态码  
                    default: 200
                    format: int32
                  code:
                    type: string
                    description: 业务端错误码
                    default: ""
                  message:
                    type: string
                    description: 错误表述信息
                    default: ""
                  value:
                    type: string
                    description: NFT Storage DID.  
                    example: "{\"Value\":\"s1655259352723101\"}"
  /api/market/storage/find:
    post:
      tags:
        - 查看存储订单
      summary: Store a file
      description: |
          ### 返回上传的文件在ipfs固定状态,filecoin密封状态
      operationId: storageFind
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              type: object
              properties:
                Value:
                  type: string
                  description: 订单编号
                  example: "{\"Value\":\"s1655259352723101\"}"
      responses:
        '200':
          description: 正常返回，状态码包含在status字段
          content:
            'application/json':
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: 状态码  
                    default: 200
                    format: int32
                  code:
                    type: string
                    description: 业务端错误码
                    default: ""
                  message:
                    type: string
                    description: 错误表述信息
                    default: ""
                  value:
                    description: json字符串  
                    $ref: '#/components/schemas/StorageInfo'
  /api/market/retrieval/list:
    post:
      tags:
        - 查看存储订单列表
      summary: Store a file
      description: |
        
        ### 返回存储订单列表
      operationId: retrievalList
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/StorageListRequest'
      responses:
        '200':
          description: 正常返回，状态码包含在status字段
          content:
            'application/json':
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: 状态码  
                    default: 200
                    format: int32
                  code:
                    type: string
                    description: 业务端错误码
                    default: ""
                  message:
                    type: string
                    description: 错误表述信息
                    default: ""
                  value:
                    description: json字符串  
                    $ref: '#/components/schemas/StorageListResponse'
  /api/v0/add:
    post:
      tags:
        - 上传文件到ipfs
      summary: Store a file
      description: |
        ### 返回
      operationId: uploadIPFS
      parameters:
        - in: query
          name: encrypt
          schema:
            type: boolean
            default: false
          description: 是否需要ipfs节点加密
        - in: query
          name: quiet
          schema:
            type: boolean
          description: Write minimal output. Required no
        - in: query
          name: quieter
          schema:
            type: boolean
          description: Write only final hash. Required no    
        - in: query
          name: silent
          schema:
            type: boolean
          description: Write no output. Required no  
        - in: query
          name: progress
          schema:
            type: boolean
          description: Stream progress data. Required no
        - in: query
          name: trickle
          schema:
            type: boolean
          description: Use trickle-dag format for dag generation. Required no
        - in: query
          name: only-hash
          schema:
            type: boolean
          description: Only chunk and hash - do not write to disk. Required no
        - in: query
          name: wrap-with-directory
          schema:
            type: boolean
          description:  Wrap files with a directory object. Required no
        - in: query
          name: chunker
          schema:
            type: string
          description:  Chunking algorithm, size-[bytes], rabin-[min]-[avg]-[max] or buzhash. Default size-262144. Required no
        - in: query
          name: pin
          schema:
            type: boolean
            default: true           
          description:  Pin this object when adding. Default true. Required no
        - in: query
          name: raw-leaves
          schema:
            type: boolean
          description:  Use raw blocks for leaf nodes. Required no
        - in: query
          name: nocopy
          schema:
            type: boolean
          description:  Add the file using filestore. Implies raw-leaves. (experimental). Required no
        - in: query
          name: fscache
          schema:
            type: boolean
          description:  Check the filestore for pre-existing blocks. (experimental). Required no
        - in: query
          name: cid-version
          schema:
            type: boolean
          description:  CID version. Defaults to 0 unless an option that depends on CIDv1 is passed. Passing version 1 will cause the raw-leaves option to default to true. Required no
        - in: query
          name: hash
          schema:
            type: string
          description:  Hash function to use. Implies CIDv1 if not sha2-256. (experimental). Default sha2-256. Required no
        - in: query
          name: inline
          schema:
            type: boolean
          description:  Inline small blocks into CIDs. (experimental). Required no
        - in: query
          name: inline-limit
          schema:
            type: integer
            default: 32
          description:  Maximum block size to inline. (experimental). Default 32. Required no     
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: 正常返回，状态码包含在status字段
          content:
            'application/json':
              schema:
                type: object
                properties:
                  Name:
                    type: string
                    description: 文件名  
                  Hash:
                    type: string
                    description: hash (cid)
                  Size:
                    type: string
                    description: 文件大小
                  Password:
                    type: string
                    description: 密码
        '500':
            description: RPC endpoint returned an error
        '400':
            description: Malformed RPC, argument type error, etc   
        '403':
            description: RPC call forbidden
        '404':
            description: RPC endpoint doesn't exist           
        '405':
            description: HTTP Method Not Allowed                                     
      servers:
        - url: https://127.0.0.1:5001
          description: ipfs私网服务器
  /api/v0/get:
      post:
        tags:
          - 从ipfs下载文件
        summary: download a file
        description: |
          ### 返回
        operationId: downloadIPFS
        parameters:
          - in: query
            name: encrypt
            schema:
              type: boolean
              default: false
            description: 是否需要ipfs节点加密
          - in: query
            name: arg
            schema:
              type: string
            description: The path to the IPFS object(s) to be outputted. Required yes
          - in: query
            name: output
            schema:
              type: string
            description: The path where the output should be stored. Required no  
          - in: query
            name: archive
            schema:
              type: boolean
            description: Output a TAR archive. Required no
          - in: query
            name: compress
            schema:
              type: boolean
            description: Compress the output with GZIP compression. Required no
          - in: query
            name: compression-level
            schema:
              type: integer
            description: The level of compression (1-9). Required no
          - in: query
            name: progress
            schema:
              type: boolean
            description: Stream progress data. Default true. Required no
          - in: query
            name: password
            schema:
              type: string
            description:  解密密钥  
        responses:
          '200':
            description: The request was processed or is being processed (streaming)
            content:
              'application/json':
                 example: {}
              'text/plain':
                 example: ""
          '500':
            description: RPC endpoint returned an error
          '400':
            description: Malformed RPC, argument type error, etc   
          '403':
            description: RPC call forbidden
          '404':
            description: RPC endpoint doesn't exist           
          '405':
            description: HTTP Method Not Allowed                 
        servers:
          - url: https://127.0.0.1:5001
            description: ipfs私网服务器
components:
  schemas:
    StorageCreateRequest:
     type: object
     properties:
        BucketID:
          description: 存储目录(0:根目录)
          type: integer
          default: 0
          format: int32
        CID:
          description: 内容id,上传IPFS后得到
          type: string
        Name:
          description: 文件名
          type: string      
        Size:
          description: 文件尺寸
          type: integer
          default: 0
          format: int64   
        Secret:
          description: ipfs加密密钥
          type: string  
        Tags:
          description: 标签
          type: array
          items:
               type: string
        Replica:
          description: 副本数
          type: integer
          default: 1
          format: int64   
        Duration:
          description: 存储时长(天)
          type: integer
          default: 0
          format: int64    
        Filecoin:
          $ref: '#/components/schemas/FilecoinInfo'
        FileName:
          description: 记录原始文件名
          type: string  
    StorageUpdateRequest:
     type: object
     properties:    
        OrderNo:
          description: 订单号
          type: string
        BucketID:
          type: object
          properties:
           Value:
            type: integer
            description: 存储目录(0:根目录)            
            default: 0
            format: int64      
        Name:
          type: object
          description: 文件名           
          properties:
           Value:
            type: string
            format: int64   
        Tags:
          type: object
          description: 标签          
          properties:
           Items:
            type: array
            items:
                 type: string             
        Replica:
          type: object
          description: 副本数             
          properties:
           Value:
            type: integer
            default: 0
            format: int64            
    StorageListRequest:
     type: object
     properties:
        Index:
          description: 页面编号
          type: integer
          default: 0
          format: int32
        Size:
          description: 每页数据总数
          type: integer
          default: 0
          format: int32   
        BucketID:
          type: object
          properties:
           Value:
            type: integer
            description: 存储目录(0:根目录)            
            default: 0
            format: int64    
        CID:
          type: object
          properties:
           Value:
            type: string
            description: 内容id,上传IPFS后得到      
        OrderNo:
          type: object
          properties:
           Value:
            type: string
            description: 订单号    
        Name:
          type: object
          properties:
           Value:
            type: string
            description: 文件名               
        Tag:
          type: object
          properties:
           Value:
            type: string
            description: 标签              
        Status:
          type: object
          properties:
           Value:
            type: integer
            description: 存储状态           
            default: 0
            format: int32   
        StartTime:
          type: object
          properties:
           Value:
            type: integer
            description: 开始时间           
            default: 0
            format: int64    
        EndTime:
          type: object
          properties:
           Value:
            type: integer
            description: 结束时间           
            default: 0
            format: int64                
     example: {"Index":1,"Size":10}
    StorageListResponse:
     type: object
     properties:    
        Total:
          description: 总数
          type: integer
          default: 1
          format: int64     
        Items:
          description: 列表
          type: array
          items:
              $ref: '#/components/schemas/StorageInfo'
    StorageInfo:
     type: object
     properties:    
        ID:
          description: 主键ID
          type: integer
          default: 1
          format: int64        
        OrderNo:
          description: 订单号
          type: string
        AppID:
          description: 存储用户所属的应用id
          type: integer
          default: 1
          format: int64             
        UserID:
          description: 存储用户id
          type: integer
          default: 1
          format: int64             
        CID:
          description: 内容id
          type: string
        Name:
          description: 文件名
          type: string          
        Size:
          description: 文件尺寸
          type: integer
          default: 1
          format: int64
        Tags:
          description: 标签
          type: array
          items:
            type: string
        Replica:
          description: 副本数
          type: integer
          default: 1
          format: int64   
        Duration:
          description: 存储时长(天)
          type: integer
          default: 1
          format: int64          
        Secret:
          description: 加密文件的密钥
          type: boolean 
        Status:
          type: integer
          enum:
            - 0
            - 1
            - 2
            - 3
          description: 存储状态 0 pending ; 1 running ; 2 finish ; 3 error
        Code:
          description: 状态码
          type: boolean 
        Msg:
          description: 状态信息
          type: boolean           
        CreateTime:
          description: 开始时间
          type: integer
          default: 1
          format: int64
        UpdateTime:
          description: 更新时间
          type: integer
          default: 1
          format: int64          
        Filecoin:
          $ref: '#/components/schemas/FilecoinInfo'
        SecretStr:
          description: 密码
          type: boolean   
        FileName:
          description: 文件名
          type: boolean   
    FilecoinInfo:
     type: object
     description: 存储到filecoin
     properties:
        Enable:
          description: 是否开启FileCoin密封备份
          type: boolean
          default: true
        MinerIDs:
          description: 可选指定miner列表
          type: array
          items:
              type: string
              description: create返回订单编号        
  securitySchemes:
    bearerAuth:
      description: |
        业务系统鉴权
        ```js
        Authorization: Idp eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiMCIsInNjb3BlcyI6WyJC56uv5pmu6YCa55So5oi3Il0sIm1ldGFkYXRhIjp7IjAiOiIxNzRhZjNiMGY4NDBmOTYyYWJjNjc5MjkyMWRjMTdiMiIsIjEiOiIwIiwiMTAiOiI1MSIsIjExIjoieGlhb21pbmciLCIxMiI6InhpYW9taW5nIiwiMTMiOiJodWFuZ2RvbmciLCIxNCI6IjI0MDAiLCIxNSI6IjMxNTM2MDAwMDAwMDAwMDAwIiwiMTYiOiJlZDI1ZmQzZi1lMzZhLTQ1OTAtYWQwYi1iOGU0ZjdmMDdhZmMiLCIyIjoiQuerr2FwcCJ9LCJleHAiOjE2ODY3MzU1NTMsImlzcyI6ImdvdG8iLCJzdWIiOiI1MSJ9.gUpH9oGopeFBv_ENapgN6hA0Rx4dOhaB6TJtry19A58h4b7XQYxDX5P_0dryJ3v4iGFUDQX0dnQJrbEbTr9T2KaBlo0Raovdc_DGMPmeuZSRxE9WHC0JpPuyJaaNN2BWg0rJSeUG7Z9ZVQnJFgfraeqsOhaJ0ypOrKrzX9FWiis
        ```    
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []