openapi: 3.0.0
info:
  title: NFT Storage API
  version: '1.0'

servers:
  - url: https://api.nft.storage
  - url: http://127.0.0.1:8787

tags:
  - name: NFT Storage
paths:
  /upload:
    post:
      tags:
        - NFT Storage
      summary: Store a file
      description: |
        Store a file with nft.storage.
        You can upload either a single file or multiple files in a directory.
        Each request to /upload is restricted to a body size of 100MB, though this does not mean you cannot upload larger files (see "Size limitations" below).

        ### Single file
        Send the POST request with `Blob`/`File` data as the request body.

        ### Multiple files
        Send the POST request as `FormData` with the header `Content-Type: multipart/form-data` set. Each part should have a `Content-Disposition` header to specify "name" (which must be "file") and "filename". e.g.

        ```
        ------WebKitFormBoundary5peilISl2YOOweQy
        Content-Disposition: form-data; name="file"; filename="image.png"
        Content-Type: image/png

        <data>
        ------WebKitFormBoundary5peilISl2YOOweQy--
        ```

        ### Content Addressed Archive (CAR) files
        You can also upload a CAR file, by setting the request body as a single CAR Blob/File object and providing the request header `Content-Type: application/car`
        Providing a CAR file allows you to pre-compute the root CID for 1 or more files, ensures that NFT.Storage will store and provide your assets with the same CID.

        ### Size limitations
        Each request to the upload endpoint is limited to a total request body size of 100MB.
        However, you can upload files larger than 100MB by packing them into a CAR file and splitting the CAR
        into chunks of less than 100MB. This strategy is used by the JavaScript client library to support uploads of large files.

        The simplest method of splitting CAR files is with the [carbites cli tool](https://github.com/nftstorage/carbites):

        ```
        npm i -g carbites-cli

        # Split a big CAR into many smaller CARs
        carbites split big.car --size 100MB --strategy treewalk
        ```

        Note that you MUST use the `treewalk` strategy, so that all the chunked CARs have the same root CID.
        Once all the CAR chunks have been uploaded, the CARs will be combined, made available via IPFS,
        and queued for storage on Filecoin.

        For more about working with CARs, see https://docs.web3.storage/how-tos/work-with-car-files

        ### Rate limits

        This API imposes rate limits to ensure quality of service. You may receive a 429 "Too many requests" error if you make more than 30 requests with the same API token within a ten second window. Upon receiving a response with a 429 status, clients should retry the failed request after a small delay. To avoid 429 responses, you may wish to implement client-side request throttling to stay within the limits (note: the JS client automatically does this).

      operationId: upload
      requestBody:
        required: true
        content:
          image/*:
            schema:
              type: string
              format: binary
          application/car:
            schema:
              type: string
              format: binary
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: array
                  items:
                    type: string
                    format: binary
          '*/*':
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/UploadResponse'
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '500':
          $ref: '#/components/responses/internalServerError'
  /:
    get:
      tags:
        - NFT Storage
      summary: List all stored files
      operationId: list
      parameters:
        - $ref: '#/components/parameters/before'
        - $ref: '#/components/parameters/limit'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ListResponse'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '500':
          $ref: '#/components/responses/internalServerError'
  /{cid}:
    get:
      tags:
        - NFT Storage
      summary: Get information for the stored file CID
      description: Includes the IPFS pinning state and the Filecoin deal state.
      operationId: status
      parameters:
        - name: cid
          in: path
          description: CID for the NFT
          required: true
          schema:
            $ref: '#/components/schemas/CID'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/GetResponse'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '500':
          $ref: '#/components/responses/internalServerError'
    delete:
      tags:
        - NFT Storage
      summary: Stop storing the content with the passed CID
      description: |
        Stop storing the content with the passed CID on nft.storage.
        - Unpin the item from the underlying IPFS pinning service.
        - Cease renewals for expired Filecoin deals involving the CID.  

        ⚠️ This does not remove the content from the network.

        - Does not terminate any established Filecoin deal.
        - Does not remove the content from other IPFS nodes in the network that already cached or pinned the CID.  

        Note: the content will remain available if another user has stored the CID with nft.storage.
      operationId: delete
      parameters:
        - name: cid
          in: path
          description: CID for the NFT
          required: true
          schema:
            $ref: '#/components/schemas/CID'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/DeleteResponse'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '500':
          $ref: '#/components/responses/internalServerError'
components:
  schemas:
    NFT:
      type: object
      properties:
        cid:
          $ref: '#/components/schemas/CID'
        size:
          description: Size in bytes of the NFT data.
          type: number
          default: 132614
        created:
          $ref: '#/components/schemas/Date'
        type:
          type: string
          example: image/jpeg
          description: MIME type of the uploaded file or 'directory' when uploading multiple files.
        scope:
          description: Name of the JWT token used to create this NFT.
          type: string
          default: default
        pin:
          $ref: '#/components/schemas/Pin'
        files:
          $ref: '#/components/schemas/Files'
        deals:
          type: array
          items:
            $ref: '#/components/schemas/Deal'
    Links:
      type: object
      properties:
        ipfs:
          type: string
          example: ipfs://bafkreidivzimqfqtoqxkrpge6bjyhlvxqs3rhe73owtmdulaxr5do5in7u
        http:
          type: string
          example: http://bafkreidivzimqfqtoqxkrpge6bjyhlvxqs3rhe73owtmdulaxr5do5in7u.ipfs.dweb.link
        file:
          type: array
          items:
            type: object
            properties:
              ipfs:
                type: string
                example: ipfs://bafkreidivzimqfqtoqxkrpge6bjyhlvxqs3rhe73owtmdulaxr5do5in7u/image.jpg
              http:
                type: string
                example: http://bafkreidivzimqfqtoqxkrpge6bjyhlvxqs3rhe73owtmdulaxr5do5in7u.ipfs.dweb.link/image.jpg
    Files:
      description: Files in the directory (only if this NFT is a directory).
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            example: logo.jpg
          type:
            type: string
            example: image/jpeg
    Deal:
      type: object
      properties:
        batchRootCid:
          type: string
          example: bafkreidivzimqfqtoqxkrpge6bjyhlvxqs3rhe73owtmdulaxr5do5in7u
        lastChange:
          type: string
          example: '2021-03-18T11:46:50.000Z'
          description: 'This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: YYYY-MM-DDTHH:MM:SSZ.'
        miner:
          description: Miner ID
          type: string
          example: f05678
        network:
          description: Filecoin network for this Deal
          type: string
          enum:
            - nerpanet
            - mainnet
        pieceCid:
          description: Piece CID string
          type: string
          example: bafkreidivzimqfqtoqxkrpge6bjyhlvxqs3rhe73owtmdulaxr5do5in7u
        status:
          description: Deal status
          type: string
          enum:
            - queued
            - proposing
            - accepted
            - failed
            - active
            - published
            - terminated
        statusText:
          type: string
          example: miner rejected my data
          description: Deal status description.
        chainDealID:
          type: number
          example: 138
          description: Identifier for the deal stored on chain.
        dealActivation:
          type: string
          example: '2021-03-18T11:46:50.000Z'
          description: 'This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: YYYY-MM-DDTHH:MM:SSZ.'
        dealExpiration:
          type: string
          example: '2021-03-18T11:46:50.000Z'
          description: 'This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: YYYY-MM-DDTHH:MM:SSZ.'
      required:
        - status
        - lastChange
    Date:
      type: string
      format: date-time
      example: '2021-03-12T17:03:07.787Z'
      description: 'This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: YYYY-MM-DDTHH:MM:SSZ.'
    CID:
      type: string
      example: bafkreidivzimqfqtoqxkrpge6bjyhlvxqs3rhe73owtmdulaxr5do5in7u
      description: Self-describing content-addressed identifiers for distributed systems. Check [spec](https://github.com/multiformats/cid) for more info.
    PinStatus:
      type: string
      enum:
        - queued
        - pinning
        - pinned
        - failed
    Pin:
      type: object
      properties:
        cid:
          $ref: '#/components/schemas/CID'
        name:
          type: string
          example: pin name
        meta:
          type: object
        status:
          $ref: '#/components/schemas/PinStatus'
        created:
          $ref: '#/components/schemas/Date'
        size:
          type: number
          example: 132614
    UploadResponse:
      type: object
      properties:
        ok:
          type: boolean
          default: true
        value:
          $ref: '#/components/schemas/NFT'
    ListResponse:
      type: object
      properties:
        ok:
          type: boolean
          default: true
        value:
          type: array
          items:
            $ref: '#/components/schemas/NFT'
    GetResponse:
      type: object
      properties:
        ok:
          type: boolean
          default: true
        value:
          type: object
          $ref: '#/components/schemas/NFT'
    CheckResponse:
      type: object
      properties:
        ok:
          type: boolean
          default: true
        value:
          type: object
          properties:
            cid:
              $ref: '#/components/schemas/CID'
            pin:
              $ref: '#/components/schemas/Pin'
            deals:
              type: array
              items:
                $ref: '#/components/schemas/Deal'
    DeleteResponse:
      type: object
      properties:
        ok:
          type: boolean
    ErrorResponse:
      type: object
      properties:
        ok:
          type: boolean
          default: false
        error:
          type: object
          properties:
            name:
              type: string
            message:
              type: string
    UnauthorizedErrorResponse:
      type: object
      properties:
        ok:
          type: boolean
          default: false
        error:
          type: object
          properties:
            name:
              type: string
              default: HTTP Error
            message:
              type: string
              default: Unauthorized
    ForbiddenErrorResponse:
      type: object
      properties:
        ok:
          type: boolean
          default: false
        error:
          type: object
          properties:
            name:
              type: string
              default: HTTP Error
            message:
              type: string
              enum: [Token is not valid, Session expired]
    DidNotFoundErrorResponse:
      type: object
      properties:
        ok:
          type: boolean
          default: false
        error:
          type: object
          properties:
            name:
              type: string
              default: DIDNotFound
            message:
              type: string
              default: User does not have a DID registered.
  securitySchemes:
    bearerAuth:
      description: |
        The NFT Storage API uses *Bearer Tokens* to authenticate requests. You can view and manage your tokens in the [NFT Storage Dashboard](https://nft.storage).   

        Your tokens carry many privileges, so be sure to keep them secure! Do not share your *secret tokens* in publicly accessible areas such as GitHub, client-side code, and so forth.   

        **Bearer authentication** (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. The name “Bearer authentication” can be understood as “give access to the bearer of this token.” The bearer token is a cryptic string, usually generated by the server in response to a login request. The client must send this token in the Authorization header when making requests to protected resources:

        ```js
        Authorization: Bearer <token>
        ```
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    unauthorized:
      description: Unauthorized
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/UnauthorizedErrorResponse'
    forbidden:
      description: Forbidden
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/ForbiddenErrorResponse'
    notFound:
      description: Not Found
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    internalServerError:
      description: Internal Server Error
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    badRequest:
      description: Bad Request
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    didNotFoundError:
      description: Bad Request
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/DidNotFoundErrorResponse'
  parameters:
    before:
      description: Return results created before provided timestamp
      name: before
      in: query
      required: false
      schema:
        type: string
        format: date-time # RFC 3339, section 5.6
      example: '2020-07-27T17:32:28Z'
    limit:
      description: Max records to return
      name: limit
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 1000
        default: 10
security:
  - bearerAuth: []
