openapi: 3.0.0
info:
  title: Helmsman NFT Storage API
  version: '1.0'

servers:
  - url: http://103.44.247.16:18001
  - url: http://127.0.0.1:8787

tags:
  - name: Helmsman NFT Storage
components:
  schemas:
    StorageCreateRequest:
     type: object
     properties:
        BucketID:
          description: 存储目录(0:根目录)
          type: integer
          default: 0
          format: int32
        CID:
          description: 内容id,上传IPFS后得到
          type: string
        Name:
          description: 文件名
          type: string      
        Size:
          description: 文件尺寸
          type: integer
          default: 0
          format: int64   
        Secret:
          description: ipfs加密密钥
          type: string  
        Tags:
          description: 标签
          type: array
          items:
               type: string
        Replica:
          description: 副本数
          type: integer
          default: 1
          format: int64   
        Duration:
          description: 存储时长(天)
          type: integer
          default: 0
          format: int64    
        Filecoin:
          $ref: '#/components/schemas/FilecoinInfo'
        FileName:
          description: 记录原始文件名
          type: string  
    StorageUpdateRequest:
     type: object
     properties:    
        OrderNo:
          description: 订单号
          type: string
        BucketID:
          type: object
          properties:
           Value:
            type: integer
            description: 存储目录(0:根目录)            
            default: 0
            format: int64      
        Name:
          type: object
          description: 文件名           
          properties:
           Value:
            type: string
            default: 0
            format: int64   
        Tags:
          type: object
          description: 标签          
          properties:
           Items:
            type: array
            items:
                 type: string             
        Replica:
          type: object
          description: 副本数             
          properties:
           Value:
            type: integer
            default: 0
            format: int64            
    StorageListRequest:
     type: object
     properties:
        Index:
          description: 页面编号
          type: integer
          default: 0
          format: int32
        Size:
          description: 每页数据总数
          type: integer
          default: 0
          format: int32   
        BucketID:
          type: object
          properties:
           Value:
            type: integer
            description: 存储目录(0:根目录)            
            default: 0
            format: int64    
        CID:
          type: object
          properties:
           Value:
            type: string
            description: 内容id,上传IPFS后得到      
        OrderNo:
          type: object
          properties:
           Value:
            type: string
            description: 订单号    
        Name:
          type: object
          properties:
           Value:
            type: string
            description: 文件名               
        Tag:
          type: object
          properties:
           Value:
            type: string
            description: 标签              
        Status:
          type: object
          properties:
           Value:
            type: integer
            description: 存储状态           
            default: 0
            format: int32   
        StartTime:
          type: object
          properties:
           Value:
            type: integer
            description: 开始时间           
            default: 0
            format: int64    
        EndTime:
          type: object
          properties:
           Value:
            type: integer
            description: 结束时间           
            default: 0
            format: int64                
    StorageListResponse:
     type: object
     properties:    
        Total:
          description: 总数
          type: integer
          default: 1
          format: int64     
        Items:
          description: 列表
          type: array
          items:
              $ref: '#/components/schemas/StorageInfo'
    StorageInfo:
     type: object
     properties:    
        ID:
          description: 主键ID
          type: integer
          default: 1
          format: int64        
        OrderNo:
          description: 订单号
          type: string
        AppID:
          description: 存储用户所属的应用id
          type: integer
          default: 1
          format: int64             
        UserID:
          description: 存储用户id
          type: integer
          default: 1
          format: int64             
        CID:
          description: 内容id
          type: string
        Name:
          description: 文件名
          type: string          
        Size:
          description: 文件尺寸
          type: integer
          default: 1
          format: int64
        Tags:
          description: 标签
          type: array
          items:
            type: string
        Replica:
          description: 副本数
          type: integer
          default: 1
          format: int64   
        Duration:
          description: 存储时长(天)
          type: integer
          default: 1
          format: int64          
        Secret:
          description: 加密文件的密钥
          type: boolean 
        Status:
          type: integer
          enum:
            - 0
            - 1
            - 2
            - 3
          description: 存储状态 0 pending ; 1 running ; 2 finish ; 3 error
        Code:
          description: 状态码
          type: boolean 
        Msg:
          description: 状态信息
          type: boolean           
        CreateTime:
          description: 开始时间
          type: integer
          default: 1
          format: int64
        UpdateTime:
          description: 更新时间
          type: integer
          default: 1
          format: int64          
        Filecoin:
          $ref: '#/components/schemas/FilecoinInfo'
        SecretStr:
          description: 密码
          type: boolean   
        FileName:
          description: 文件名
          type: boolean   
    FilecoinInfo:
     type: object
     description: 存储到filecoin
     properties:
        Enable:
          description: 是否开启FileCoin密封备份
          type: boolean
          default: true
        MinerIDs:
          description: 可选指定miner列表
          type: array
          items:
              type: string
              description: create返回订单编号        
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []